name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --user 1001

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          echo 'nobody ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/nobody
          sudo -u nobody ./test.sh
