name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create local-aur.pkg.tar.zst
        run: |
          docker run --rm -v "$PWD":/code archlinux sh -c '
            set -e
            pacman -Sy --noconfirm sudo base-devel git python
            cp -r /code /build
            chown -R nobody:nobody /build
            echo "nobody ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/nobody
            sudo -u nobody /build/build.sh
            cd /build
            cp "$(sudo -u nobody makepkg --packagelist)" /code/local-aur.pkg.tar.zst
          '

      - name: Test
        run: ./test.sh "$PWD/local-aur.pkg.tar.zst"
