name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker

    steps:
      - uses: actions/checkout@v2
      - name: Install pacman
        run: apk add pacman-makepkg sudo
      - name: Give nobody sudo
        run: "echo 'nobody ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/nobody"
      - name: Test
        run: sudo -u nobody ./test.sh
